version: '3'

# Volumes #####################################################################
volumes:
  citydb_data:
    # external: true

# Networks ####################################################################
networks:
  net:
    driver: overlay
    attachable: true

# Services ####################################################################
services:
  # 3DCityDB ------------------------------------------------------------------
  citydb:
    image: 3dcitydb/3dcitydb-pg
    # container_name: citydb
    networks:
      - net
    ports:
      - 5432:5432
    shm_size: '1gb'
    environment:
      # POSTGRES_DB: postgres
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SRID: 25832
    volumes:
      - citydb_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Adapt and uncomment for optimized DB settings with: https://pgtune.leopard.in.ua/#/
    # command:
    #   postgres
    #   -c max_connections=100
    #   -c shared_buffers=3GB
    #   -c effective_cache_size=9GB
    #   -c maintenance_work_mem=768MB
    #   -c checkpoint_completion_target=0.7
    #   -c wal_buffers=16MB
    #   -c default_statistics_target=100
    #   -c random_page_cost=1.1
    #   -c effective_io_concurrency=200
    #   -c work_mem=31457kB
    #   -c min_wal_size=1GB
    #   -c max_wal_size=4GB
    #   -c max_worker_processes=2
    #   -c max_parallel_workers_per_gather=1
    #   -c max_parallel_workers=2
    #   -c max_parallel_maintenance_workers=1

  # Web Feature Service (WFS) -------------------------------------------------
  wfs:
    image: 3dcitydb/wfs
    # container_name: wfs
    networks:
      - net
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      citydb:
        condition: service_healthy
    environment:
      # CITYDB_TYPE: postgresql|oracle
      # CITYDB_PORT: 5432
      # CITYDB_SCHEMA: theCityDBSchemaName
      CITYDB_HOST: citydb
      CITYDB_NAME: postgres
      CITYDB_USERNAME: postgres
      CITYDB_PASSWORD: postgres